Module7 task1
htmlacademy-vue/835389-pizza-1 pull request #7
Opened 2022-01-30 14:36 UTC by alexrud-a

2022-01-30 16:58 UTC, Djaler commented on src/frontend/src/views/__tests__/Login.spec.js
> +    expect(actions.Auth.login).toHaveBeenCalledWith(
тут у тебя не срабатывает вызов экшена login, потому что он действительно не вызывается. Срабатывает `if (this.form.email.length && this.form.password.length) {`. Нужно предварительно в тесте перед сабмитом закинуть какие-то значения в эти инпуты. Ты их в propsData передаёшь, но в этом компоненте же пропсов нет

2022-01-30 16:59 UTC, Djaler commented on src/frontend/src/views/__tests__/Login.spec.js
> +    expect(router.push("/")).toHaveBeenCalled();
и вот так проверять тоже не получится. Во первых, у тебя router - это настоящий роутер, не мок. Ты можешь создать простой объект типа `const router = { push: jest.fn() }`.
И проверять вызов нужно вот так `expect(router.push).toHaveBeenCalledWith('/')`

2022-01-30 17:02 UTC, Djaler commented on src/frontend/src/modules/builder/__tests__/BuilderPizzaView.spec.js
> +    expect(wrapper.find("[data-test='price']").element.textContent).toBe(
`wrapper.find("[data-test='price']").text()`

2022-01-30 17:07 UTC, Djaler commented on src/frontend/src/views/__tests__/Profile.spec.js
> +    propsData.isFormAddress = true;
кстати, вот тут ты меняешь состояние propsData, который общий для всех тестов. Есть опасность того, что другой тест будет зависеть от этого изменения. Хорошо бы инициализировать propsData в beforeEach, например, чтоб избежать такого

2022-01-30 17:08 UTC, Djaler commented on src/frontend/src/views/__tests__/Profile.spec.js
> +  let propsData = {
ну и опять таки, этот компонент же пропсы не принимает. Чтобы в его data сменился isFormAddress на true, тебе нужно сэмулировать какие-то пользовательские действия, которые к этому приводят. Например, нажатие на кнопку `Добавить новый адрес`

2022-01-30 17:10 UTC, Djaler commented on src/frontend/src/views/__tests__/Profile.spec.js
> +    const addressesItems = wrapper.findAll("[data-test='user-address']");
а тут забыла вызвать createComponent

2022-01-30 17:12 UTC, Djaler commented on src/frontend/src/views/__tests__/Profile.spec.js
> +    list: addresses,
тут должно быть `value: addresses`, судя по тому, как эта мутация дергается в экшене getAddresses

2022-01-30 17:17 UTC, Djaler commented on src/frontend/src/modules/cart/__tests__/CartMisc.spec.js
> +    property: miscItems,
тут аналогично, должно быть
```
entity: "misc",
    list: miscItems,
    ```

2022-01-30 17:17 UTC, Djaler commented on src/frontend/src/modules/cart/__tests__/CartMisc.spec.js
> +    expect(items.length).toHaveLength(miscItems.length);
`expect(items).toHaveLength(miscItems.length);`

2022-01-30 17:23 UTC, Djaler commented on src/frontend/src/views/__tests__/Orders.spec.js
> +    expect(wrapper.exists()).toBeTruthy();
по вот этому месту - у тебя геттер formattedOrders использует данные в том числе из модуля Builder. Поэтому тебе нужно в тесте эти данные тоже задать мутациями

2022-01-30 17:23 UTC, Djaler commented on src/frontend/src/views/__tests__/Orders.spec.js
> +    expect(wrapper.exists()).toBeTruthy();
К слову, в геттере немного странный код обнаружил
![image](https://user-images.githubusercontent.com/7964583/151710110-c73605eb-0dd8-48b5-af39-5359e11c6095.png)
Тут явно должен быть `el.id == pizza.doughId`

2022-02-20 05:59 UTC, enotke requested changes

2022-02-20 05:59 UTC, enotke commented on src/frontend/src/common/components/__tests__/SelectorItem.spec.js
> +    expect(wrapper.find("span").element.textContent.trim()).toBe(
Обычно для этого используют функцию text. `wrapper.find("span").text()`

2022-02-20 05:59 UTC, enotke commented on src/frontend/src/common/components/__tests__/ItemCounter.spec.js
> +    propsData.count = 0;
У тебя propsData это общий объект для всех тестов, по идее он должен быть либо readonly либо сбрасываться перед каждым тестом. Если изменить порядок тестов, то они сломаются, а так быть не должно.

2022-02-20 05:59 UTC, enotke commented on src/frontend/src/modules/cart/__tests__/CartProducts.spec.js
> +        `${item.price * item.qty} ₽`
При таком подходе можно начать писать тесты на тесты) Обычно в тесты не содержат каких-либо условий или вычислений. Ты просто подаешь какие-то данные на входе и проверяешь результат работы компонента.

2022-02-20 05:59 UTC, enotke commented on src/frontend/src/modules/cart/__tests__/CartDelivery.spec.js
> +      val: street.element.value,
Нужно проверять ожидаемое значение - "2". В тестах проверки должны быть явными. Вот этот тест например не работает. Так как по логике в street.element.value должно находиться значение "2", но там находится пустая строка

2022-02-20 21:08 UTC, merged